// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMNciAwB_gKTp0oN462vJe0ssHg2Mgxg',
    appId: '1:223578029045:web:8b33a68a44b9f6a7d9bebc',
    messagingSenderId: '223578029045',
    projectId: 'praticesfirebase-ade37',
    authDomain: 'praticesfirebase-ade37.firebaseapp.com',
    storageBucket: 'praticesfirebase-ade37.appspot.com',
    measurementId: 'G-2NJEYB1KWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtiYyGosIDN_iBVHI183J2HzVFyrqTkRM',
    appId: '1:223578029045:android:8d3fcde89602207dd9bebc',
    messagingSenderId: '223578029045',
    projectId: 'praticesfirebase-ade37',
    storageBucket: 'praticesfirebase-ade37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0jin43vNNPSEBZm-aXqEfgPd9j4th4kg',
    appId: '1:223578029045:ios:7e28514ec330448bd9bebc',
    messagingSenderId: '223578029045',
    projectId: 'praticesfirebase-ade37',
    storageBucket: 'praticesfirebase-ade37.appspot.com',
    iosClientId: '223578029045-0v7la4e0upkmlbdp7pd02mpu6sauri8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.praticesFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0jin43vNNPSEBZm-aXqEfgPd9j4th4kg',
    appId: '1:223578029045:ios:cebc420529107b07d9bebc',
    messagingSenderId: '223578029045',
    projectId: 'praticesfirebase-ade37',
    storageBucket: 'praticesfirebase-ade37.appspot.com',
    iosClientId: '223578029045-vt786vjna3vbip0kvl9jm9ml9r0mjtbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.praticesFirebase.RunnerTests',
  );
}
